#!/usr/bin/env python3
"""Turn the Select T (watsonx Orchestrate) cockpit page into the MaaS360 Cold Call page.

    python3 tools/adapt-select-t.py reference/orchestrate-only.html cold-call.html

Keeps the Select T page's markup, styles and renderer as they are, and applies a few
small, marked changes:
  - loads the MaaS360 product (data/maas360-product.js) instead of the inline product list
  - loads assets/maas360-extras.js, which adds MaaS360 content to the same sections
  - MaaS360 title, brand, version tag, Sales Guide page menu, and a "Your city" input
  - renderer hooks: {city} fill, extras refresh on industry/persona change, richer
    objection cards (then-step, other wordings, consult tag), Proof as the default opener
Re-run it on a newer Select T file to pick up the owner's changes.
"""
import re, sys

src, dst = sys.argv[1], sys.argv[2]
s = open(src, encoding='utf-8').read()

def rep(old, new, count=1, regex=False):
    global s
    n = len(re.findall(old, s)) if regex else s.count(old)
    if n < 1:
        sys.exit('adapt: pattern not found: ' + old[:80])
    s = re.sub(old, new, s, count=count) if regex else s.replace(old, new, count)

# ---- header comment + title
rep('<!--\n  Select T — Cold Call Cockpit (product-aware)', '<!--\n  MaaS360 Cold Call Cockpit, built on the Select T cockpit page (generated by tools/adapt-select-t.py).\n  Content: data/coldcall-maas360.json -> data/maas360-product.js (npm run build).\n\n  Select T — Cold Call Cockpit (product-aware)')
rep(r'<title>[^<]*</title>', '<title>MaaS360 · Cold Call Cockpit · Select T</title>', regex=True)

# ---- brand -> MaaS360 Sales Guide, plus a Sales Guide page menu in the select slot
rep('<a class="brand" href="./" aria-label="Cold Call Cockpit home">', '<a class="brand" href="index.html" aria-label="MaaS360 Sales Guide home">')
rep('<span class="brand-name">Select T <span class="brand-sub">Cold Call Cockpit</span></span>',
    '<span class="brand-name">MaaS360 <span class="brand-sub">Cold Call Cockpit</span></span>')
rep('      <label class="nav-select">',
    '''      <label class="nav-pages">
        <span class="sr-only">Sales Guide page</span>
        <select id="pageSelect" aria-label="Go to a Sales Guide page" onchange="location.href=this.value">
          <option value="index.html">Hub</option>
          <option value="prospecting.html">Prospecting</option>
          <option value="cold-call.html" selected>Cold Call</option>
          <option value="resources.html">Resources</option>
          <option value="onboarding.html">Onboarding</option>
          <option value="rep-alignment.html">Rep Alignment</option>
          <option value="territory-map.html">Territory Map</option>
        </select>
      </label>
      <label class="nav-select">''')
m = re.search(r'\.nav-select select\{[^}]*\}', s)
rep('</style>', '/* MaaS360: Sales Guide page menu, styled like the product menu */\n' + m.group(0).replace('.nav-select select', '.nav-pages select') +
    '\n@media (max-width:720px){ .nav-pages{order:5; flex:1 1 100%;} .nav-pages select{max-width:none; width:100%;} }\n</style>')

# ---- "Your city" input (the MaaS360 scripts say "down here in [Your City]")
rep('''<label>Your callback number<input''', '''<label>Your city<input type="text" data-in="city" placeholder="e.g., Austin"></label>
          <label>Your callback number<input''')

# ---- product data: MaaS360 entry + extras instead of the inline product list
start = s.index('<script>\n/* ===================== PRODUCT DATA')
end = s.index('</script>', start) + len('</script>')
s = s[:start] + '''<script src="data/maas360-product.js"></script>
  <link rel="stylesheet" href="assets/maas360-extras.css">
  <script src="assets/maas360-extras.js"></script>''' + s[end:]

# ---- version tag
rep(r'<div class="version-tag">[^<]*</div>', '<div class="version-tag">Version 2026-10-06 · MaaS360</div>', regex=True)

# ---- renderer hooks (all marked "MaaS360:")
rep("      peerco: val(i.peerco, 'peer company')",
    "      peerco: val(i.peerco, 'peer company'),\n      city: val(i.city, 'Your City') // MaaS360: scripts say \"down here in [Your City]\"")
rep('''  function refreshContext() {
    renderUseCaseGrid();''', '''  // MaaS360: let assets/maas360-extras.js re-render its blocks for the current selection
  function extRefresh() { if (window.MAAS360_EXT) window.MAAS360_EXT.refresh({ industry: state.industry, persona: state.persona, product: state.product }); }
  function refreshContext() {
    extRefresh();
    renderUseCaseGrid();''')
rep('''        $$('#personaPills .pill').forEach(function (x) { x.classList.toggle('active', x === b); x.setAttribute('aria-selected', x === b); });
        fill();''', '''        $$('#personaPills .pill').forEach(function (x) { x.classList.toggle('active', x === b); x.setAttribute('aria-selected', x === b); });
        extRefresh(); // MaaS360
        fill();''')
rep('''    // reset opener tabs + objection cards
    setOpener(state.opener);''', '''    extRefresh(); // MaaS360
    // reset opener tabs + objection cards
    setOpener(state.opener);''')
# objection cards: MaaS360 markup, optional continue, then-step, other wordings, tag
rep('''      return '<div class="obj prod" data-obj>' +
        '<button class="obj-head" type="button"><span class="q">"' + esc(o.q) + '"' + (targeted ? ' <span class="tgt">for you</span>' : '') + '</span><span class="chev">▾</span></button>' +''',
'''      var X = window.MAAS360_EXT; // MaaS360: formats lines that carry delivery cues
      var sayL = function (t) { return X ? X.quote(t) : '"' + esc(t) + '"'; };
      return '<div class="obj prod" data-obj>' +
        '<button class="obj-head" type="button"><span class="q">"' + esc(o.q) + '"' + (targeted ? ' <span class="tgt">for you</span>' : '') + (o.tag ? ' <span class="tgt">' + esc(o.tag) + '</span>' : '') + '</span><span class="chev">▾</span></button>' +''')
rep('''          '<div class="ob-row"><span class="ob-l">Acknowledge</span><p class="say copyable">"' + esc(o.ack) + '"</p></div>' +
          '<div class="ob-row"><span class="ob-l">Explore</span><p class="say copyable">"' + esc(o.explore) + '"</p></div>' +
          '<div class="ob-row"><span class="ob-l">Continue</span><p class="say copyable">"' + esc(o.cont) + '"</p></div>' +''',
'''          '<div class="ob-row"><span class="ob-l">' + (o.explore ? 'Acknowledge' : 'Say') + '</span><p class="say copyable">' + sayL(o.ack) + '</p></div>' +
          (o.explore ? '<div class="ob-row"><span class="ob-l">Explore</span><p class="say copyable">' + sayL(o.explore) + '</p></div>' : '') +
          (o.cont ? '<div class="ob-row"><span class="ob-l">Continue</span><p class="say copyable">' + sayL(o.cont) + '</p></div>' : '') +
          (X && o.then ? X.thenRow(o) : '') +''')
rep('''          '<span class="goes">Goes after: ' + esc(o.goes) + '</span>' +
          linksHtml(o.links, 'Back it up') +''', '''          (X && o.alts && o.alts.length ? X.altRows(o) : '') +
          '<span class="goes">Goes after: ' + esc(o.goes) + '</span>' +
          linksHtml(o.links, 'Back it up') +''')

# Proof is the default opener style for MaaS360 (the old cockpit's default)
n = len(re.findall(r"opener: load\('stcc-opener', 'peer'\)|opener: 'peer'", s))
if n:
    s = re.sub(r"opener: (load\('stcc-opener', )?'peer'\)?", lambda m: m.group(0).replace("'peer'", "(window.MAAS360_DEFAULT_OPENER || 'peer')"), s, count=1)

open(dst, 'w', encoding='utf-8').write(s)
print('adapt: wrote', dst)
