#!/usr/bin/env node
// Builds data/maas360-product.js from data/coldcall-maas360.json.
//
// The output is the MaaS360 entry in the Select T cockpit's own product format
// (window.SELECT_T_PRODUCTS, see the FIELD GUIDE in the Select T page), plus the
// full MaaS360 data as window.MAAS360 for content the template has no field for
// (rendered into the same sections by assets/maas360-extras.js).
// The same entry can be pasted into the Select T sandbox's SELECT_T_PRODUCTS list.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const D = JSON.parse(fs.readFileSync(path.join(ROOT, 'data/coldcall-maas360.json'), 'utf8'));
const OUT = path.join(ROOT, 'data/maas360-product.js');

// plain text for fields the template escapes and prints as-is
const plain = (s) => String(s || '').replace(/\*\*/g, '').replace(/\[\[[^\]]*\]\]/g, '').replace(/\s+/g, ' ').trim();

const entry = {
  id: 'maas360',
  name: D.product.name,
  full: D.product.full,
  group: 'Automation',
  segment: 'Secure Access & Identity',
  tier: 'keycore',
  value: plain(D.value),
  topic: D.topic,
  owns: D.owns,
  ownerTeam: D.ownerTeam,
  focus: D.focus,
  costs: D.costs,
  incumbents: D.incumbents,
  triggers: D.triggers,
  personas: D.personas.map((p) => ({
    role: p.role, plural: p.plural, hypothesis: p.hypothesis, peer: p.peer,
    // no persona "value": the old variants are fragments, so every persona keeps the full value line
    id: p.id,
  })),
  // "General" is the template's "All industries" pill, so it isn't listed as an industry
  industries: D.industries.filter((i) => i.id !== 'general').map((i) => ({ id: i.id, label: i.label, type: i.type, triggers: [] })),
  useCases: [],
  references: [],
  objSource: 'from the MaaS360 cold call cockpit',
  objections: D.objections.map((o) => ({
    id: o.id,
    q: o.q,
    really: '',
    industries: o.industries || [],
    useCases: [],
    tag: o.openers && o.openers.length ? 'Consult offer' : (o.exit ? 'Exit' : ''),
    ack: o.ack, explore: o.explore || '', cont: o.cont || '',
    then: o.then || '', alts: o.alts || [], contSource: o.contSource || '',
    goes: o.goes,
    press: o.press || '',
    links: [],
  })),
  resources: [{ label: 'MaaS360 product page', url: 'https://www.ibm.com/products/maas360' }],
  proof: D.proof.map((p) => ({ stat: plain(p.stat), line: plain(p.line), src: p.src + ' · ' + plain(p.label) })),
  reviewed: !!D.meta.reviewed,
};

const js = `/* GENERATED by tools/build-product.mjs from data/coldcall-maas360.json. Do not edit by hand:
   edit the JSON, then run \`npm run build\`. */
window.MAAS360 = ${JSON.stringify(D)};
window.SELECT_T_PRODUCTS = [${JSON.stringify(entry, null, 2)}];
`;
const check = process.argv.includes('--check');
if (check) {
  const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (cur !== js) { console.error('build: data/maas360-product.js is out of date. Run `npm run build`.'); process.exit(1); }
  console.log('build: data/maas360-product.js is up to date');
} else {
  fs.writeFileSync(OUT, js);
  console.log(`build: wrote data/maas360-product.js (${entry.personas.length} personas, ${entry.industries.length} industries, ${entry.objections.length} objections, ${entry.proof.length} proof points)`);
}
